#Gradle
org.gradle.jvmargs=-Xmx64g -XX:MaxMetaspaceSize=8g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.workers.max=2
#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx32g -XX:+UseG1GC
kotlin.js.compiler=ir
kotlin.native.cacheKind=static
#MPP
kotlin.mpp.enableCInteropCommonization=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
io.kotest.multiplatform.compiler.plugin.enabled=false
kotest.compiler.plugin.enabled=false

#Project
basePackage=dev.ohs.fhir.model
mavenGroupId=dev.ohs.fhir
mavenArtifactId=fhir-model
androidNamespace=dev.ohs.fhir
