[versions]
android-gradle-plugin = "8.13.0"
android-compileSdk = "35"
android-minSdk = "24"
bignum = "0.3.10"
kotest = "6.1.11"
kotlin = "2.3.20"
kotlin-poet = "2.0.0"
kotlinx-datetime = "0.7.1"
kotlinx-serialization-json = "1.8.1"
kotlinx-serialization-protobuf = "1.8.1"
ksp = "2.3.6"
maven-publish = "0.36.0"
spotless = "7.0.1"

[libraries]
bignum = { group = "com.ionspin.kotlin", name = "bignum", version.ref = "bignum"}
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
kotest-framework-engine = {module = "io.kotest:kotest-framework-engine", version.ref = "kotest"}
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-poet" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization-protobuf" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }